# The region for which all metrics passing through this server will be persisted
region: useast

# Whether this server is running on a secure port
accessedViaHttps: false

# Topic for publishing metrics to
metricsTopic: metrics

# Topic for publishing domain events to
eventsTopic: events

databaseConfiguration:
# vertica | influxdb
  #databaseType: influxdb
  databaseType: influxdb

kafka:
  brokerUris:
    - 192.168.10.4:9092
  zookeeperUris:
    - 192.168.10.4:2181
  healthCheckTopic: healthcheck

mysql:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.10.4:3306/mon?connectTimeout=5000&autoReconnect=true
  user: monapi
  password: password
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true

vertica:
  driverClass: com.vertica.jdbc.Driver
  url: jdbc:vertica://192.168.10.4/mon
  user: mon_api
  password: password
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 4
  maxSize: 32
  checkConnectionWhileIdle: false


influxDB:
  name: mon
  replicationFactor: 1
  url: http://localhost:8086
  user:  root
  password: root

middleware:
  enabled: true
  serviceIds: 100
  endpointIds: 160
  serverVIP: 192.168.10.5
  serverPort: 5000
  connTimeout: 500
  connSSLClientAuth: true
  keystore: /etc/ssl/hpmiddleware-keystore.jks
  keystorePass: changeit
  truststore: /etc/ssl/hpmiddleware-truststore.jks
  truststorePass: changeit
  connPoolMaxActive: 3
  connPoolMaxIdle: 3
  connPoolEvictPeriod: 600000
  connPoolMinIdleTime: 600000
  connRetryTimes: 2
  connRetryInterval: 50
  rolesToMatch: [user, domainuser, domainadmin, _member_]
  adminAuthMethod: password
  adminUser: admin
  adminPassword: password
  adminToken: ADMIN
  timeToCacheToken: 600
  maxTokenCacheSize: 1048576

server:
  applicationConnectors:
    - type: http
      maxRequestHeaderSize: 16KiB  # Allow large headers used by keystone tokens


# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG
    com.hpcloud: debug

  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: # TODO

    - type: file
      currentLogFilename: /var/log/mon-api/mon-api.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/mon-api/mon-api-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
      logFormat: # TODO

    - type: syslog
      host: localhost
      port: 514
      facility: local0
      threshold: ALL
      logFormat: # TODO
